import jsPDF from "jspdf";

// Brand colors (matches the app's purple/blue gradient theme)
const BRAND_PRIMARY = [206, 96, 240]; // #CE60F0
const BRAND_SECONDARY = [70, 78, 254]; // #464EFE
const TEXT_DARK = [30, 32, 48];
const TEXT_MUTED = [110, 114, 140];
const RULE_COLOR = [220, 220, 230];
const TABLE_HEADER_BG = [243, 238, 253];

/**
 * Very small markdown -> block parser. Good enough for the structured
 * headings/lists/tables ShePilot's AI prompts are instructed to produce,
 * without pulling in a heavier markdown/PDF dependency.
 */
function parseMarkdownBlocks(content = "") {
  const rawLines = content.replace(/\r\n/g, "\n").split("\n");
  const blocks = [];
  let i = 0;

  const stripInline = (s) =>
    s
      .replace(/\*\*(.*?)\*\*/g, "$1")
      .replace(/\*(.*?)\*/g, "$1")
      .replace(/`(.*?)`/g, "$1")
      .trim();

  while (i < rawLines.length) {
    const line = rawLines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      i++;
      continue;
    }

    // Table: a line starting with | followed by a separator row
    if (trimmed.startsWith("|") && rawLines[i + 1]?.trim().match(/^\|[\s:|-]+\|$/)) {
      const tableLines = [];
      let j = i;
      while (j < rawLines.length && rawLines[j].trim().startsWith("|")) {
        tableLines.push(rawLines[j].trim());
        j++;
      }
      const rows = tableLines
        .filter((_, idx) => idx !== 1) // drop the --- separator row
        .map((row) =>
          row
            .replace(/^\|/, "")
            .replace(/\|$/, "")
            .split("|")
            .map((cell) => stripInline(cell))
        );
      blocks.push({ type: "table", rows });
      i = j;
      continue;
    }

    // Headings
    const h3 = trimmed.match(/^###\s+(.*)/);
    const h2 = trimmed.match(/^##\s+(.*)/);
    const h1 = trimmed.match(/^#\s+(.*)/);
    if (h1) {
      blocks.push({ type: "h1", text: stripInline(h1[1]) });
      i++;
      continue;
    }
    if (h2) {
      blocks.push({ type: "h2", text: stripInline(h2[1]) });
      i++;
      continue;
    }
    if (h3) {
      blocks.push({ type: "h3", text: stripInline(h3[1]) });
      i++;
      continue;
    }

    // Bullet list item
    const bullet = trimmed.match(/^[-*•]\s+(.*)/);
    if (bullet) {
      blocks.push({ type: "bullet", text: stripInline(bullet[1]) });
      i++;
      continue;
    }

    // Numbered list item
    const numbered = trimmed.match(/^(\d+)[.)]\s+(.*)/);
    if (numbered) {
      blocks.push({ type: "numbered", index: numbered[1], text: stripInline(numbered[2]) });
      i++;
      continue;
    }

    // Plain paragraph
    blocks.push({ type: "p", text: stripInline(trimmed) });
    i++;
  }

  return blocks;
}

export function downloadPDF(title, content) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const marginX = 18;
  const marginTop = 38;
  const marginBottom = 20;
  const contentWidth = pageWidth - marginX * 2;

  const safeTitle = title || "ShePilot AI Result";
  const today = new Date().toLocaleString();

  let page = 1;
  let cursorY = marginTop;

  const drawBrandMark = (x, y) => {
    doc.setFillColor(...BRAND_SECONDARY);
    doc.circle(x, y, 5, "F");
    doc.setFillColor(...BRAND_PRIMARY);
    doc.circle(x + 2, y - 1, 4, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text("S", x + 0.6, y + 1.6);
  };

  const drawHeader = () => {
    drawBrandMark(marginX + 4, 14);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.text("SHEPILOT OS", marginX + 12, 12.5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(17);
    doc.setTextColor(...TEXT_DARK);
    doc.text(safeTitle, marginX, 25, { maxWidth: contentWidth });

    doc.setDrawColor(...BRAND_PRIMARY);
    doc.setLineWidth(0.8);
    doc.line(marginX, 30, pageWidth - marginX, 30);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(`Generated by ShePilot AI • ${today}`, marginX, 34.5);
  };

  const drawFooter = () => {
    doc.setDrawColor(...RULE_COLOR);
    doc.setLineWidth(0.4);
    doc.line(marginX, pageHeight - 15, pageWidth - marginX, pageHeight - 15);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.text("ShePilot OS — AI Operating System for Founders", marginX, pageHeight - 9);
    doc.text(`Page ${page}`, pageWidth - marginX, pageHeight - 9, { align: "right" });
  };

  const ensureSpace = (needed) => {
    if (cursorY + needed > pageHeight - marginBottom) {
      drawFooter();
      doc.addPage();
      page++;
      cursorY = marginTop;
    }
  };

  drawHeader();

  const blocks = parseMarkdownBlocks(content);

  blocks.forEach((block) => {
    if (block.type === "h1") {
      ensureSpace(14);
      cursorY += 3;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(...TEXT_DARK);
      doc.text(block.text, marginX, cursorY);
      cursorY += 9;
      return;
    }

    if (block.type === "h2") {
      ensureSpace(12);
      cursorY += 4;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13.5);
      doc.setTextColor(...BRAND_SECONDARY);
      doc.text(block.text, marginX, cursorY);
      cursorY += 7.5;
      return;
    }

    if (block.type === "h3") {
      ensureSpace(10);
      cursorY += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11.5);
      doc.setTextColor(...BRAND_PRIMARY);
      doc.text(block.text, marginX, cursorY);
      cursorY += 6.5;
      return;
    }

    if (block.type === "bullet" || block.type === "numbered") {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10.5);
      doc.setTextColor(...TEXT_DARK);

      const prefix = block.type === "bullet" ? "•" : `${block.index}.`;
      const indent = 6;
      const lines = doc.splitTextToSize(block.text, contentWidth - indent - 4);

      ensureSpace(lines.length * 5.6 + 2);
      doc.text(prefix, marginX, cursorY);
      doc.text(lines, marginX + indent, cursorY);
      cursorY += lines.length * 5.6 + 2;
      return;
    }

    if (block.type === "table") {
      const rows = block.rows.filter((r) => r.some((c) => c.length));
      if (!rows.length) return;

      const colCount = rows[0].length;
      const colWidth = contentWidth / colCount;
      const cellPadding = 2.5;

      rows.forEach((row, rowIdx) => {
        // Measure row height first
        doc.setFont("helvetica", rowIdx === 0 ? "bold" : "normal");
        doc.setFontSize(9.5);

        const cellLines = row.map((cell) =>
          doc.splitTextToSize(cell, colWidth - cellPadding * 2)
        );
        const rowHeight =
          Math.max(...cellLines.map((l) => l.length), 1) * 4.6 + cellPadding * 2;

        ensureSpace(rowHeight);

        if (rowIdx === 0) {
          doc.setFillColor(...TABLE_HEADER_BG);
          doc.rect(marginX, cursorY - 4, contentWidth, rowHeight, "F");
        }

        doc.setDrawColor(...RULE_COLOR);
        doc.setLineWidth(0.3);

        for (let c = 0; c <= colCount; c++) {
          const x = marginX + c * colWidth;
          doc.line(x, cursorY - 4, x, cursorY - 4 + rowHeight);
        }
        doc.line(marginX, cursorY - 4, marginX + contentWidth, cursorY - 4);
        doc.line(
          marginX,
          cursorY - 4 + rowHeight,
          marginX + contentWidth,
          cursorY - 4 + rowHeight
        );

        doc.setTextColor(...TEXT_DARK);
        cellLines.forEach((lines, colIdx) => {
          doc.text(
            lines,
            marginX + colIdx * colWidth + cellPadding,
            cursorY
          );
        });

        cursorY += rowHeight;
      });

      cursorY += 4;
      return;
    }

    // Paragraph
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(...TEXT_DARK);
    const lines = doc.splitTextToSize(block.text, contentWidth);
    ensureSpace(lines.length * 5.6 + 2);
    doc.text(lines, marginX, cursorY);
    cursorY += lines.length * 5.6 + 3;
  });

  drawFooter();

  const fileName = safeTitle
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 80);

  doc.save(`${fileName}.pdf`);
}
